import { StreamLanguage } from '@codemirror/language'

// The ten languages the spec names explicitly. Full LR-parser support via
// dedicated @codemirror/lang-* packages, loaded lazily so the initial bundle
// doesn't pay for languages nobody picks.
export const PRIMARY_LANGUAGES = [
  { id: 'javascript', name: 'JavaScript', load: () => import('@codemirror/lang-javascript').then((m) => m.javascript()) },
  { id: 'python', name: 'Python', load: () => import('@codemirror/lang-python').then((m) => m.python()) },
  { id: 'html', name: 'HTML', load: () => import('@codemirror/lang-html').then((m) => m.html()) },
  { id: 'css', name: 'CSS', load: () => import('@codemirror/lang-css').then((m) => m.css()) },
  { id: 'json', name: 'JSON', load: () => import('@codemirror/lang-json').then((m) => m.json()) },
  { id: 'sql', name: 'SQL', load: () => import('@codemirror/lang-sql').then((m) => m.sql()) },
  { id: 'markdown', name: 'Markdown', load: () => import('@codemirror/lang-markdown').then((m) => m.markdown()) },
  { id: 'cpp', name: 'C++', load: () => import('@codemirror/lang-cpp').then((m) => m.cpp()) },
  { id: 'java', name: 'Java', load: () => import('@codemirror/lang-java').then((m) => m.java()) },
  { id: 'rust', name: 'Rust', load: () => import('@codemirror/lang-rust').then((m) => m.rust()) }
]

// Everything else, via @codemirror/legacy-modes' StreamLanguage — no LR
// parser, but highlighting and indentation for roughly a hundred more
// languages at almost no bundle cost. Each loader is a static import path
// (not a templated one) so the production bundler can code-split every
// entry into its own lazy chunk; a templated path is unanalyzable by Rollup
// and would break `vite build`.
export const LEGACY_LANGUAGES = [
  { id: 'c', name: 'C', load: () => import('@codemirror/legacy-modes/mode/clike').then((m) => StreamLanguage.define(m.c)) },
  { id: 'csharp', name: 'C#', load: () => import('@codemirror/legacy-modes/mode/clike').then((m) => StreamLanguage.define(m.csharp)) },
  { id: 'scala', name: 'Scala', load: () => import('@codemirror/legacy-modes/mode/clike').then((m) => StreamLanguage.define(m.scala)) },
  { id: 'kotlin', name: 'Kotlin', load: () => import('@codemirror/legacy-modes/mode/clike').then((m) => StreamLanguage.define(m.kotlin)) },
  { id: 'shader', name: 'Shader (GLSL)', load: () => import('@codemirror/legacy-modes/mode/clike').then((m) => StreamLanguage.define(m.shader)) },
  { id: 'nesc', name: 'nesC', load: () => import('@codemirror/legacy-modes/mode/clike').then((m) => StreamLanguage.define(m.nesC)) },
  { id: 'objectivec', name: 'Objective-C', load: () => import('@codemirror/legacy-modes/mode/clike').then((m) => StreamLanguage.define(m.objectiveC)) },
  { id: 'objectivecpp', name: 'Objective-C++', load: () => import('@codemirror/legacy-modes/mode/clike').then((m) => StreamLanguage.define(m.objectiveCpp)) },
  { id: 'squirrel', name: 'Squirrel', load: () => import('@codemirror/legacy-modes/mode/clike').then((m) => StreamLanguage.define(m.squirrel)) },
  { id: 'ceylon', name: 'Ceylon', load: () => import('@codemirror/legacy-modes/mode/clike').then((m) => StreamLanguage.define(m.ceylon)) },
  { id: 'dart', name: 'Dart', load: () => import('@codemirror/legacy-modes/mode/clike').then((m) => StreamLanguage.define(m.dart)) },
  { id: 'apl', name: 'APL', load: () => import('@codemirror/legacy-modes/mode/apl').then((m) => StreamLanguage.define(m.apl)) },
  { id: 'asciiarmor', name: 'PGP (ASCII armor)', load: () => import('@codemirror/legacy-modes/mode/asciiarmor').then((m) => StreamLanguage.define(m.asciiArmor)) },
  { id: 'asterisk', name: 'Asterisk dialplan', load: () => import('@codemirror/legacy-modes/mode/asterisk').then((m) => StreamLanguage.define(m.asterisk)) },
  { id: 'brainfuck', name: 'Brainfuck', load: () => import('@codemirror/legacy-modes/mode/brainfuck').then((m) => StreamLanguage.define(m.brainfuck)) },
  { id: 'clojure', name: 'Clojure', load: () => import('@codemirror/legacy-modes/mode/clojure').then((m) => StreamLanguage.define(m.clojure)) },
  { id: 'cmake', name: 'CMake', load: () => import('@codemirror/legacy-modes/mode/cmake').then((m) => StreamLanguage.define(m.cmake)) },
  { id: 'cobol', name: 'COBOL', load: () => import('@codemirror/legacy-modes/mode/cobol').then((m) => StreamLanguage.define(m.cobol)) },
  { id: 'coffeescript', name: 'CoffeeScript', load: () => import('@codemirror/legacy-modes/mode/coffeescript').then((m) => StreamLanguage.define(m.coffeeScript)) },
  { id: 'commonlisp', name: 'Common Lisp', load: () => import('@codemirror/legacy-modes/mode/commonlisp').then((m) => StreamLanguage.define(m.commonLisp)) },
  { id: 'crystal', name: 'Crystal', load: () => import('@codemirror/legacy-modes/mode/crystal').then((m) => StreamLanguage.define(m.crystal)) },
  { id: 'scss', name: 'SCSS', load: () => import('@codemirror/legacy-modes/mode/css').then((m) => StreamLanguage.define(m.sCSS)) },
  { id: 'less', name: 'LESS', load: () => import('@codemirror/legacy-modes/mode/css').then((m) => StreamLanguage.define(m.less)) },
  { id: 'gss', name: 'Closure Stylesheets (GSS)', load: () => import('@codemirror/legacy-modes/mode/css').then((m) => StreamLanguage.define(m.gss)) },
  { id: 'cypher', name: 'Cypher', load: () => import('@codemirror/legacy-modes/mode/cypher').then((m) => StreamLanguage.define(m.cypher)) },
  { id: 'd', name: 'D', load: () => import('@codemirror/legacy-modes/mode/d').then((m) => StreamLanguage.define(m.d)) },
  { id: 'diff', name: 'Diff', load: () => import('@codemirror/legacy-modes/mode/diff').then((m) => StreamLanguage.define(m.diff)) },
  { id: 'dockerfile', name: 'Dockerfile', load: () => import('@codemirror/legacy-modes/mode/dockerfile').then((m) => StreamLanguage.define(m.dockerFile)) },
  { id: 'dtd', name: 'DTD', load: () => import('@codemirror/legacy-modes/mode/dtd').then((m) => StreamLanguage.define(m.dtd)) },
  { id: 'dylan', name: 'Dylan', load: () => import('@codemirror/legacy-modes/mode/dylan').then((m) => StreamLanguage.define(m.dylan)) },
  { id: 'ebnf', name: 'EBNF', load: () => import('@codemirror/legacy-modes/mode/ebnf').then((m) => StreamLanguage.define(m.ebnf)) },
  { id: 'ecl', name: 'ECL', load: () => import('@codemirror/legacy-modes/mode/ecl').then((m) => StreamLanguage.define(m.ecl)) },
  { id: 'eiffel', name: 'Eiffel', load: () => import('@codemirror/legacy-modes/mode/eiffel').then((m) => StreamLanguage.define(m.eiffel)) },
  { id: 'elm', name: 'Elm', load: () => import('@codemirror/legacy-modes/mode/elm').then((m) => StreamLanguage.define(m.elm)) },
  { id: 'erlang', name: 'Erlang', load: () => import('@codemirror/legacy-modes/mode/erlang').then((m) => StreamLanguage.define(m.erlang)) },
  { id: 'factor', name: 'Factor', load: () => import('@codemirror/legacy-modes/mode/factor').then((m) => StreamLanguage.define(m.factor)) },
  { id: 'fcl', name: 'FCL', load: () => import('@codemirror/legacy-modes/mode/fcl').then((m) => StreamLanguage.define(m.fcl)) },
  { id: 'forth', name: 'Forth', load: () => import('@codemirror/legacy-modes/mode/forth').then((m) => StreamLanguage.define(m.forth)) },
  { id: 'fortran', name: 'Fortran', load: () => import('@codemirror/legacy-modes/mode/fortran').then((m) => StreamLanguage.define(m.fortran)) },
  { id: 'gas', name: 'GNU Assembler (x86)', load: () => import('@codemirror/legacy-modes/mode/gas').then((m) => StreamLanguage.define(m.gas)) },
  { id: 'gas-arm', name: 'GNU Assembler (ARM)', load: () => import('@codemirror/legacy-modes/mode/gas').then((m) => StreamLanguage.define(m.gasArm)) },
  { id: 'gherkin', name: 'Gherkin', load: () => import('@codemirror/legacy-modes/mode/gherkin').then((m) => StreamLanguage.define(m.gherkin)) },
  { id: 'go', name: 'Go', load: () => import('@codemirror/legacy-modes/mode/go').then((m) => StreamLanguage.define(m.go)) },
  { id: 'groovy', name: 'Groovy', load: () => import('@codemirror/legacy-modes/mode/groovy').then((m) => StreamLanguage.define(m.groovy)) },
  { id: 'haskell', name: 'Haskell', load: () => import('@codemirror/legacy-modes/mode/haskell').then((m) => StreamLanguage.define(m.haskell)) },
  { id: 'haxe', name: 'Haxe', load: () => import('@codemirror/legacy-modes/mode/haxe').then((m) => StreamLanguage.define(m.haxe)) },
  { id: 'hxml', name: 'HXML', load: () => import('@codemirror/legacy-modes/mode/haxe').then((m) => StreamLanguage.define(m.hxml)) },
  { id: 'http', name: 'HTTP', load: () => import('@codemirror/legacy-modes/mode/http').then((m) => StreamLanguage.define(m.http)) },
  { id: 'idl', name: 'IDL', load: () => import('@codemirror/legacy-modes/mode/idl').then((m) => StreamLanguage.define(m.idl)) },
  { id: 'jinja2', name: 'Jinja2', load: () => import('@codemirror/legacy-modes/mode/jinja2').then((m) => StreamLanguage.define(m.jinja2)) },
  { id: 'julia', name: 'Julia', load: () => import('@codemirror/legacy-modes/mode/julia').then((m) => StreamLanguage.define(m.julia)) },
  { id: 'livescript', name: 'LiveScript', load: () => import('@codemirror/legacy-modes/mode/livescript').then((m) => StreamLanguage.define(m.liveScript)) },
  { id: 'lua', name: 'Lua', load: () => import('@codemirror/legacy-modes/mode/lua').then((m) => StreamLanguage.define(m.lua)) },
  { id: 'mathematica', name: 'Mathematica', load: () => import('@codemirror/legacy-modes/mode/mathematica').then((m) => StreamLanguage.define(m.mathematica)) },
  { id: 'mbox', name: 'Mbox', load: () => import('@codemirror/legacy-modes/mode/mbox').then((m) => StreamLanguage.define(m.mbox)) },
  { id: 'mirc', name: 'mIRC', load: () => import('@codemirror/legacy-modes/mode/mirc').then((m) => StreamLanguage.define(m.mirc)) },
  { id: 'ocaml', name: 'OCaml', load: () => import('@codemirror/legacy-modes/mode/mllike').then((m) => StreamLanguage.define(m.oCaml)) },
  { id: 'fsharp', name: 'F#', load: () => import('@codemirror/legacy-modes/mode/mllike').then((m) => StreamLanguage.define(m.fSharp)) },
  { id: 'sml', name: 'SML', load: () => import('@codemirror/legacy-modes/mode/mllike').then((m) => StreamLanguage.define(m.sml)) },
  { id: 'modelica', name: 'Modelica', load: () => import('@codemirror/legacy-modes/mode/modelica').then((m) => StreamLanguage.define(m.modelica)) },
  { id: 'mscgen', name: 'Mscgen', load: () => import('@codemirror/legacy-modes/mode/mscgen').then((m) => StreamLanguage.define(m.mscgen)) },
  { id: 'msgenny', name: 'Msgenny', load: () => import('@codemirror/legacy-modes/mode/mscgen').then((m) => StreamLanguage.define(m.msgenny)) },
  { id: 'xu', name: 'Xù', load: () => import('@codemirror/legacy-modes/mode/mscgen').then((m) => StreamLanguage.define(m.xu)) },
  { id: 'mumps', name: 'MUMPS', load: () => import('@codemirror/legacy-modes/mode/mumps').then((m) => StreamLanguage.define(m.mumps)) },
  { id: 'nginx', name: 'Nginx config', load: () => import('@codemirror/legacy-modes/mode/nginx').then((m) => StreamLanguage.define(m.nginx)) },
  { id: 'nsis', name: 'NSIS', load: () => import('@codemirror/legacy-modes/mode/nsis').then((m) => StreamLanguage.define(m.nsis)) },
  { id: 'ntriples', name: 'NTriples', load: () => import('@codemirror/legacy-modes/mode/ntriples').then((m) => StreamLanguage.define(m.ntriples)) },
  { id: 'octave', name: 'Octave', load: () => import('@codemirror/legacy-modes/mode/octave').then((m) => StreamLanguage.define(m.octave)) },
  { id: 'oz', name: 'Oz', load: () => import('@codemirror/legacy-modes/mode/oz').then((m) => StreamLanguage.define(m.oz)) },
  { id: 'pascal', name: 'Pascal', load: () => import('@codemirror/legacy-modes/mode/pascal').then((m) => StreamLanguage.define(m.pascal)) },
  { id: 'pegjs', name: 'PEG.js grammar', load: () => import('@codemirror/legacy-modes/mode/pegjs').then((m) => StreamLanguage.define(m.pegjs)) },
  { id: 'perl', name: 'Perl', load: () => import('@codemirror/legacy-modes/mode/perl').then((m) => StreamLanguage.define(m.perl)) },
  { id: 'pig', name: 'Pig Latin', load: () => import('@codemirror/legacy-modes/mode/pig').then((m) => StreamLanguage.define(m.pig)) },
  { id: 'powershell', name: 'PowerShell', load: () => import('@codemirror/legacy-modes/mode/powershell').then((m) => StreamLanguage.define(m.powerShell)) },
  { id: 'properties', name: '.properties / INI', load: () => import('@codemirror/legacy-modes/mode/properties').then((m) => StreamLanguage.define(m.properties)) },
  { id: 'protobuf', name: 'Protocol Buffers', load: () => import('@codemirror/legacy-modes/mode/protobuf').then((m) => StreamLanguage.define(m.protobuf)) },
  { id: 'pug', name: 'Pug', load: () => import('@codemirror/legacy-modes/mode/pug').then((m) => StreamLanguage.define(m.pug)) },
  { id: 'puppet', name: 'Puppet', load: () => import('@codemirror/legacy-modes/mode/puppet').then((m) => StreamLanguage.define(m.puppet)) },
  { id: 'cython', name: 'Cython', load: () => import('@codemirror/legacy-modes/mode/python').then((m) => StreamLanguage.define(m.cython)) },
  { id: 'q', name: 'Q', load: () => import('@codemirror/legacy-modes/mode/q').then((m) => StreamLanguage.define(m.q)) },
  { id: 'r', name: 'R', load: () => import('@codemirror/legacy-modes/mode/r').then((m) => StreamLanguage.define(m.r)) },
  { id: 'rpm-changes', name: 'RPM changes', load: () => import('@codemirror/legacy-modes/mode/rpm').then((m) => StreamLanguage.define(m.rpmChanges)) },
  { id: 'rpm-spec', name: 'RPM spec', load: () => import('@codemirror/legacy-modes/mode/rpm').then((m) => StreamLanguage.define(m.rpmSpec)) },
  { id: 'ruby', name: 'Ruby', load: () => import('@codemirror/legacy-modes/mode/ruby').then((m) => StreamLanguage.define(m.ruby)) },
  { id: 'sas', name: 'SAS', load: () => import('@codemirror/legacy-modes/mode/sas').then((m) => StreamLanguage.define(m.sas)) },
  { id: 'sass', name: 'Sass (indented)', load: () => import('@codemirror/legacy-modes/mode/sass').then((m) => StreamLanguage.define(m.sass)) },
  { id: 'scheme', name: 'Scheme', load: () => import('@codemirror/legacy-modes/mode/scheme').then((m) => StreamLanguage.define(m.scheme)) },
  { id: 'shell', name: 'Shell', load: () => import('@codemirror/legacy-modes/mode/shell').then((m) => StreamLanguage.define(m.shell)) },
  { id: 'sieve', name: 'Sieve', load: () => import('@codemirror/legacy-modes/mode/sieve').then((m) => StreamLanguage.define(m.sieve)) },
  { id: 'smalltalk', name: 'Smalltalk', load: () => import('@codemirror/legacy-modes/mode/smalltalk').then((m) => StreamLanguage.define(m.smalltalk)) },
  { id: 'solr', name: 'Solr', load: () => import('@codemirror/legacy-modes/mode/solr').then((m) => StreamLanguage.define(m.solr)) },
  { id: 'sparql', name: 'SPARQL', load: () => import('@codemirror/legacy-modes/mode/sparql').then((m) => StreamLanguage.define(m.sparql)) },
  { id: 'spreadsheet', name: 'Spreadsheet', load: () => import('@codemirror/legacy-modes/mode/spreadsheet').then((m) => StreamLanguage.define(m.spreadsheet)) },
  { id: 'stex', name: 'LaTeX / sTeX', load: () => import('@codemirror/legacy-modes/mode/stex').then((m) => StreamLanguage.define(m.stex)) },
  { id: 'stylus', name: 'Stylus', load: () => import('@codemirror/legacy-modes/mode/stylus').then((m) => StreamLanguage.define(m.stylus)) },
  { id: 'swift', name: 'Swift', load: () => import('@codemirror/legacy-modes/mode/swift').then((m) => StreamLanguage.define(m.swift)) },
  { id: 'tcl', name: 'Tcl', load: () => import('@codemirror/legacy-modes/mode/tcl').then((m) => StreamLanguage.define(m.tcl)) },
  { id: 'textile', name: 'Textile', load: () => import('@codemirror/legacy-modes/mode/textile').then((m) => StreamLanguage.define(m.textile)) },
  { id: 'tiddlywiki', name: 'TiddlyWiki', load: () => import('@codemirror/legacy-modes/mode/tiddlywiki').then((m) => StreamLanguage.define(m.tiddlyWiki)) },
  { id: 'tiki', name: 'Tiki wiki', load: () => import('@codemirror/legacy-modes/mode/tiki').then((m) => StreamLanguage.define(m.tiki)) },
  { id: 'toml', name: 'TOML', load: () => import('@codemirror/legacy-modes/mode/toml').then((m) => StreamLanguage.define(m.toml)) },
  { id: 'troff', name: 'Troff', load: () => import('@codemirror/legacy-modes/mode/troff').then((m) => StreamLanguage.define(m.troff)) },
  { id: 'ttcn', name: 'TTCN', load: () => import('@codemirror/legacy-modes/mode/ttcn').then((m) => StreamLanguage.define(m.ttcn)) },
  { id: 'ttcn-cfg', name: 'TTCN config', load: () => import('@codemirror/legacy-modes/mode/ttcn-cfg').then((m) => StreamLanguage.define(m.ttcnCfg)) },
  { id: 'turtle', name: 'Turtle', load: () => import('@codemirror/legacy-modes/mode/turtle').then((m) => StreamLanguage.define(m.turtle)) },
  { id: 'vb', name: 'Visual Basic', load: () => import('@codemirror/legacy-modes/mode/vb').then((m) => StreamLanguage.define(m.vb)) },
  { id: 'vbscript', name: 'VBScript', load: () => import('@codemirror/legacy-modes/mode/vbscript').then((m) => StreamLanguage.define(m.vbScript)) },
  { id: 'vbscript-asp', name: 'VBScript (ASP)', load: () => import('@codemirror/legacy-modes/mode/vbscript').then((m) => StreamLanguage.define(m.vbScriptASP)) },
  { id: 'velocity', name: 'Velocity', load: () => import('@codemirror/legacy-modes/mode/velocity').then((m) => StreamLanguage.define(m.velocity)) },
  { id: 'verilog', name: 'Verilog', load: () => import('@codemirror/legacy-modes/mode/verilog').then((m) => StreamLanguage.define(m.verilog)) },
  { id: 'tlv', name: 'TL-Verilog', load: () => import('@codemirror/legacy-modes/mode/verilog').then((m) => StreamLanguage.define(m.tlv)) },
  { id: 'vhdl', name: 'VHDL', load: () => import('@codemirror/legacy-modes/mode/vhdl').then((m) => StreamLanguage.define(m.vhdl)) },
  { id: 'wast', name: 'WebAssembly (WAT)', load: () => import('@codemirror/legacy-modes/mode/wast').then((m) => StreamLanguage.define(m.wast)) },
  { id: 'webidl', name: 'WebIDL', load: () => import('@codemirror/legacy-modes/mode/webidl').then((m) => StreamLanguage.define(m.webIDL)) },
  { id: 'xml', name: 'XML', load: () => import('@codemirror/legacy-modes/mode/xml').then((m) => StreamLanguage.define(m.xml)) },
  { id: 'xquery', name: 'XQuery', load: () => import('@codemirror/legacy-modes/mode/xquery').then((m) => StreamLanguage.define(m.xQuery)) },
  { id: 'yacas', name: 'Yacas', load: () => import('@codemirror/legacy-modes/mode/yacas').then((m) => StreamLanguage.define(m.yacas)) },
  { id: 'yaml', name: 'YAML', load: () => import('@codemirror/legacy-modes/mode/yaml').then((m) => StreamLanguage.define(m.yaml)) },
  { id: 'z80', name: 'Z80 assembly', load: () => import('@codemirror/legacy-modes/mode/z80').then((m) => StreamLanguage.define(m.z80)) },
  { id: 'ez80', name: 'eZ80 assembly', load: () => import('@codemirror/legacy-modes/mode/z80').then((m) => StreamLanguage.define(m.ez80)) }
]

export const ALL_LANGUAGES = [...PRIMARY_LANGUAGES, ...LEGACY_LANGUAGES]

export function findLanguage (id) {
  return ALL_LANGUAGES.find((lang) => lang.id === id)
}
